--QUERY 7. List businesses where their categories have at most 1 distinct subcategory.
SELECT B.BUSINESS_ID, B.BUSINESS_NAME
FROM BUSINESS B , BUSINESS_CATEGORY BC
WHERE B.BUSINESS_CATEGORY = BC.BUSINESS_CATEGORY_ID AND BC.BUSINESS_CATEGORY_ID IN (SELECT DISTINCT S.BUSINESS_CATEGORY_ID   
																					FROM BUSINESS_CATEGORY BC, BUSINESS_CATEGORY_SUBCATEGORY S
																					WHERE  S.BUSINESS_CATEGORY_ID  = BC.BUSINESS_CATEGORY_ID
																					GROUP BY S.BUSINESS_CATEGORY_ID
																					HAVING COUNT(S.SUBCATEGORY)<= 1)
ORDER BY B.BUSINESS_ID ;